# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      # Every weekday, Monday to Friday, at 5am UTC
      interval: "daily"
    labels:
      - "dependabot"
    allow:
      # Update direct and indirect dependencies
      - dependency-type: "all"
    # CHANGEME: Remove the following line to activate Dependabot (this is only to prevent Dependabot from creating PRs in this template repository)
    open-pull-requests-limit: 0
