version: '3.4'
services:
  # Usage: docker-compose up rails
  # Runs a rails server, access it at localhost:RAILS_PORT (the value of the environment variable RAILS_PORT is below)
  rails:
    build: .
    depends_on:
      - database
    environment:
      - RAILS_PORT=80 # Do not forget to change ports below when changing this
    ports:
      - '80:80'
    volumes:
      - .:/app
      - gems:/gems # Use cache from gems volume

  # Usage: docker-compose up database
  # Other services depend on this. It shouldn't be run by itself
  database:
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=database_dev
    image: postgres:10.2
    ports:
      - '5432:5432'
volumes:
  # Cache gems from 'bundle install'
  gems:
