version: '3.4'
services:
  # Usage: docker-compose up rails
  # Runs a rails server, access it at localhost:RAILS_PORT (the value of the environment variable RAILS_PORT is below)
  rails:
    build: .
    depends_on:
      - database
    environment:
      - RAILS_PORT=80 # Do not forget to change ports below when changing this
    ports:
      - '80:80'
    volumes:
      - .:/app # Same as $WORKDIR from Dockerfile
      - gems:/gems # Cache gems from 'bundler' commands (install, update, etc...) in gems volume

  # Usage: docker-compose up bundle
  # For convenience, run it whenever changing the Gemfile
  bundle:
    build: .
    command: bash -c "(bundle check || bundle install)"
    volumes:
      - .:/app # Same as $WORKDIR from Dockerfile
      - gems:/gems # Cache gems from 'bundler' commands (install, update, etc...) in gems volume

  # Usage:
  #   - Run all specs: docker-compose up specs
  #   - Run specific specs: docker-compose run specs bash -c 'bundle exec rspec spec/models/user_spec.rb:12'
  specs:
    build: .
    command: bash -c "(bundle check || bundle install) && bundle exec rspec"
    volumes:
      - .:/app # Same as $WORKDIR from Dockerfile
      - gems:/gems # Cache gems from 'bundler' commands (install, update, etc...) in gems volume

  # Usage: docker-compose up database
  # Other services depend on this. It shouldn't be run by itself
  database:
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=database_dev
    image: postgres:10.2
    ports:
      - '5432:5432'
volumes:
  # Cache gems from 'bundler' commands (install, update, etc...)
  gems:
